### ISSUE TITLE
How can i update zenject to the latest?

### ISSUE THREAD

**Issue by auvgfw** [cgarciae/karma#9]
Hi
The latest karma is built on zenject 4.7 which not support unity 5.6.
can i update zenject by my self?

**Comment by SacredSkull** [comment]
I did the same for 4.7 in PR #5. I might be able to do it today - I also have a few improvements I wanted to commit anyway.

This looks like a major change (4.7 to 5.x) so will probably have some breaking changes. 4.2 to 4.7 even had breaking changes, but reading the changelog makes it sound like they've just moved some stuff around rather than a complete refactor. The easiest way to do it would be to simply rename the old library folder and put the 5.x release in its place - then start fixing the compiler errors. Once those are done then you can fix the more annoying runtime exceptions. :smirk:

**Comment by cgarciae** [comment]
@auvgfw @SacredSkull All help is welcomed! I've been out of Unity3D lately but I am very happy to help you improving Karma.
